openapi: 3.0.0
info:
  description: Documentation for domain-crawler
  version: 1.0.0
  title: Domain Crawler Service
paths:
  /crawl:
    post:
      tags:
        - Crawl
      summary: "Crawl different set of urls"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CrawlRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CrawlResponse"
        "429":
          description: Too Many Requests
components:
  schemas:
    CrawlRequest:
      type: object
      properties:
        urls:
          type: array
          items:
            type: string
        keywords:
          type: array
          items:
            type: string
      required:
        - urls
        - keywords

    CrawlResponse:
      type: object
      properties:
        results:
          type: array
          items: 
            $ref: "#/components/schemas/SuccessResult"
        errors:
          type: array
          items: 
            $ref: "#/components/schemas/ErrorResult"

      required:
        - results

    SuccessResult:
      type: object
      properties:
        url:
          type: string
        title:
          type: string
        meta_descriptions:
          type: array
          items:
            type: string
        links:
          type: array
          items:
            type: string
        keyword_counts:
          type: object
      required:
        - url
        - title
        - meta_descriptions
        - links
        - keyword_counts

    ErrorResult:
      type: object
      properties:
        url:
          type: string
        error:
          type: string
      required:
        - url
        - error
